=== Tzeentche/ATM/XmlDances/class.dtd
<!ELEMENT school (class+,principal_name)>
        <!ATTLIST principal_name #REQUIRED>
        <!ELEMENT class (student+, class_average)>
        <!ATTLIST class
                name CDATA #REQUIRED
                teacher CDATA #REQUIRED
                >
        <!ELEMENT principal_name (#PCDATA)>
        <!ELEMENT student (name,last_name,average_grade)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT last_name (#PCDATA)>
        <!ELEMENT average_grade (#PCDATA)>
        <!ELEMENT class_average (#PCDATA)>

=== Tzeentche/ATM/HW3/src/xmlFiles/Sample1.xml
<?xml version="1.1" encoding="windows-1251"?>
<!--<!DOCTYPE school SYSTEM "class.dtd">-->
<school>
    <principal_name>Noname Lastname</principal_name>
    <class name="1A" teacher="Ivanova I.I">
        <student>
            <name>Alex</name>
            <last_name>Strakh</last_name>
            <average_grade>6.4</average_grade>
        </student>
        <student>
            <name>Ihar</name>
            <last_name>Vavilau</last_name>
            <average_grade>8</average_grade>
        </student>
        <student>
            <name>Palina</name>
            <last_name>Suprun</last_name>
            <average_grade>9</average_grade>
        </student>
        <student>
            <name>Olga</name>
            <last_name>Razumova</last_name>
            <average_grade>4.7</average_grade>
        </student>
        <class_average>"7.4"</class_average>
    </class>
</school>
